app:
  Name: eagle
  Version: 1.0.0
  PprofPort: :5555
  Mode: debug                 # debug, release, test
  JwtSecret: JWT_SECRET
  JwtTimeout: 86400
  CookieName: jwt-token
  SSL: true
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false

Http:
  Addr: :8080
  ReadTimeout: 3s
  WriteTimeout: 3s
Grpc:
  Addr: :9090
  ReadTimeout: 5s
  WriteTimeout: 5s

logger:
  Development: false
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json                          # json or console
  Level: info                             # log level, INFO, WARN, ERROR
  Name: eagle
  Writers: console                        # There are 2 options: file, console. Selecting file will record the log to the log file specified by logger_file. Selecting console will output the log to standard output. Of course, both can be selected at the same time.
  LoggerFile: /tmp/log/eagle.log
  LoggerWarnFile: /tmp/log/eagle.wf.log
  LoggerErrorFile: /tmp/log/eagle.err.log
  LogRollingPolicy: daily
  LogRotateDate: 1
  LogRotateSize: 1
  LogBackupCount: 7

orm:
  Name: eagle                     # Name database
  Addr: localhost:3306            # If it is docker, it can be replaced with the corresponding service name, eg: db:3306
  UserName: root
  Password: 123456
  ShowLog: true                   # whether to print all SQL logs
  MaxIdleConn: 10                 # The maximum number of idle connections, 0 means use the default size of 2, less than 0 means do not use the connection pool
  MaxOpenConn: 60                 # The maximum number of open connections, which needs to be less than the number of max_connections in the database configuration
  ConnMaxLifeTime: 4h             # The maximum survival time of a single connection is recommended to be set slightly smaller than the database timeout period (wait_timeout).

mysql:
  Dsn: "root:123456@tcp(localhost:3306)/eagle?timeout=2s&readTimeout=5s&writeTimeout=5s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
  ShowLog: true                   # Whether to print SQL log
  MaxIdleConn: 10                 # The maximum number of idle connections, 0 means use the default size of 2, less than 0 means do not use the connection pool
  MaxOpenConn: 60                 # The maximum number of open connections, which needs to be less than the number of max_connections in the database configuration
  ConnMaxLifeTime: 4000           # The maximum survival time of a single connection is recommended to be set slightly smaller than the database timeout period (wait_timeout).
  QueryTimeout: 200
  ExecTimeout: 200
  TranTimeout: 200
  Braker:                         # Fuse Configuration
    window: 3s
    sleep: 100ms
    bucket: 100
    ratio: 0.5
    request: 100


redis:
  Addr: 127.0.0.1:6379
  Password: ""
  DB: 0
  MinIdleConn: 200
  DialTimeout: 60s
  ReadTimeout: 500ms
  WriteTimeout: 500ms
  PoolSize: 100
  PoolTimeout: 240s
  IsTrace: true

email:
  Host: SMTP_HOST       # SMTP address
  Port: 25              # port
  Username: USER        # username
  Password: PASSWORD    # password
  Name: eagle           # sender name
  Address: SEND_EMAIL   # sender email
  ReplyTo: EMAIL        # Reply address
  KeepAlive: 30         # connection hold time

web:
  Name: eagle
  Domain: http://eagle.com
  Secret: abcdefg
  Static: /data/static

cookie:
  Name: jwt-token
  MaxAge: 86400
  Secure: false
  HttpOnly: true
  Domain: http://eagle.com
  Secret: abcdefg

qiniu:
  AccessKey: ACCESS_KEY
  SecretKey: SECRET_KEY
  CdnURL: http://cdn.eagle.com
  SignatureID: signature_id  # SMS signature id
  TemplateID: template_id    # template id

metrics:
  Url: 0.0.0.0:7070
  ServiceName: api

MongoDB:
  URI: "mongodb://localhost:27017"
  User: "admin"
  Password: "admin"
  DB: "eagle"
